import { GET_CLIENT_SESSION, FILTER_SERVICE_METRICS } from 'graphql/queries';

export const ClientDevicesDetailsQueryMock = {
  getClientSession: {
    success: {
      request: {
        query: GET_CLIENT_SESSION,
        variables: {
          customerId: 2,
          macAddress: '74:9c:00:01:45:ae',
        },
      },
      result: {
        data: {
          getClientSession: [
            {
              id: '74:9c:00:01:45:ae',
              macAddress: '74:9c:00:01:45:ae',
              ipAddress: '192.168.10.171',
              hostname: 'hostName-128213363803566',
              ssid: 'Default-SSID-1597172801679',
              radioType: 'is2dot4GHz',
              signal: '-56',
              manufacturer: null,
              equipment: {
                name: 'AP 40',
                __typename: 'Equipment',
              },
              details: {
                model_type: 'ClientSessionDetails',
                sessionId: 1597172802575,
                authTimestamp: null,
                assocTimestamp: 1597172185365,
                assocInternalSC: null,
                ipTimestamp: null,
                disconnectByApTimestamp: null,
                disconnectByClientTimestamp: null,
                timeoutTimestamp: null,
                firstDataSentTimestamp: null,
                firstDataRcvdTimestamp: null,
                ipAddress: '192.168.10.171',
                radiusUsername: null,
                ssid: 'Default-SSID-1597172801679',
                radioType: 'is2dot4GHz',
                lastEventTimestamp: 0,
                hostname: 'hostName-128213363803566',
                apFingerprint: 'fp 74:9c:00:01:45:ae',
                userAgentStr: null,
                lastRxTimestamp: null,
                lastTxTimestamp: null,
                cpUsername: null,
                dhcpDetails: {
                  model_type: 'ClientDhcpDetails',
                  dhcpServerIp: '192.168.0.1',
                  primaryDns: '8.8.8.8',
                  secondaryDns: '192.168.0.1',
                  subnetMask: '192.168.0.255',
                  gatewayIp: '192.168.0.1',
                  leaseStartTimestamp: 1597160501039,
                  leaseTimeInSeconds: 14400,
                  firstRequestTimestamp: null,
                  firstOfferTimestamp: null,
                  firstDiscoverTimestamp: null,
                  nakTimestamp: null,
                  fromInternal: false,
                  associationId: 1597172802575,
                },
                eapDetails: null,
                metricDetails: {
                  model_type: 'ClientSessionMetricDetails',
                  rxBytes: 6048860,
                  txBytes: 6400949,
                  totalRxPackets: null,
                  totalTxPackets: null,
                  rxMbps: 91.4453,
                  txMbps: 65.76753,
                  rssi: -56,
                  snr: -51,
                  rxRateKbps: null,
                  txRateKbps: null,
                  lastMetricTimestamp: 0,
                  lastRxTimestamp: null,
                  lastTxTimestamp: null,
                  classification: null,
                  txDataFrames: null,
                  txDataFramesRetried: null,
                  rxDataFrames: null,
                },
                isReassociation: null,
                disconnectByApReasonCode: null,
                disconnectByClientReasonCode: null,
                disconnectByApInternalReasonCode: null,
                disconnectByClientInternalReasonCode: null,
                portEnabledTimestamp: null,
                is11RUsed: null,
                is11KUsed: null,
                is11VUsed: null,
                securityType: 'PSK',
                steerType: null,
                previousValidSessionId: null,
                lastFailureDetails: null,
                firstFailureDetails: null,
                associationStatus: null,
                dynamicVlan: null,
                assocRssi: null,
                priorSessionId: null,
                priorEquipmentId: null,
                classificationName: null,
                associationState: null,
                eapSuccessTimestamp: null,
                eapKey4Timestamp: null,
              },
              __typename: 'ClientSession',
            },
          ],
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: GET_CLIENT_SESSION,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
  filterServiceMetrics: {
    success: {
      request: {
        query: FILTER_SERVICE_METRICS,
        variables: {
          customerId: 2,
          fromTime: '1234',
          toTime: '1234',
          clientMacs: ['74:9c:00:01:45:ae'],
          dataTypes: ['Client'],
          limit: 1000,
        },
      },
      result: {
        data: {
          filterServiceMetrics: {
            items: [],
            context: {
              lastPage: true,
              cursor:
                'bnVsbEBAQHsibW9kZWxfdHlwZSI6IkNvbnRleHRDaGlsZHJlbiIsImNoaWxkcmVuIjp7fX1AQEBudWxs',
              __typename: 'PaginationContext',
            },
            __typename: 'ServiceMetricPagination',
          },
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: FILTER_SERVICE_METRICS,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
};
