import {
  GET_EQUIPMENT,
  GET_ALL_PROFILES,
  GET_ALL_FIRMWARE,
  FILTER_SERVICE_METRICS,
} from 'graphql/queries';
import { UPDATE_EQUIPMENT, UPDATE_EQUIPMENT_FIRMWARE } from 'graphql/mutations';

export const APDetailsQueryMock = {
  getEquipment: {
    success: {
      request: {
        query: GET_EQUIPMENT,
        variables: {
          id: '1',
        },
      },
      result: {
        data: {
          getEquipment: {
            id: '1',
            equipmentType: 'AP',
            inventoryId: 'ap-1',
            customerId: '2',
            profileId: '6',
            locationId: '4',
            name: 'AP 1',
            latitude: null,
            longitude: null,
            serial: 'serial-ap-1',
            lastModifiedTimestamp: '1597172801891',
            details: {
              model_type: 'ApElementConfiguration',
              equipmentModel: 'ecw5211',
              elementConfigVersion: 'AP-V1',
              equipmentType: 'AP',
              deviceMode: 'standaloneAP',
              gettingIP: 'dhcp',
              staticIP: null,
              staticIpMaskCidr: null,
              staticIpGw: null,
              gettingDNS: 'dhcp',
              staticDnsIp1: null,
              staticDnsIp2: null,
              peerInfoList: [],
              deviceName: 'Default Device Name',
              locationData: null,
              locallyConfiguredMgmtVlan: 0,
              locallyConfigured: false,
              deploymentType: 'CEILING',
              syntheticClientEnabled: null,
              frameReportThrottleEnabled: true,
              antennaType: 'OMNI',
              costSavingEventsEnabled: true,
              forwardMode: 'BRIDGE',
              radioMap: {
                is2dot4GHz: {
                  model_type: 'ElementRadioConfiguration',
                  radioType: 'is2dot4GHz',
                  channelNumber: 6,
                  manualChannelNumber: 6,
                  backupChannelNumber: 11,
                  autoChannelSelection: true,
                  channelBandwidth: 'is20MHz',
                  bannedChannels: [],
                  allowedChannels: [],
                  rxCellSizeDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  probeResponseThresholdDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  clientDisconnectThresholdDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  eirpTxPower: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: 18,
                  },
                  bestApEnabled: null,
                  neighbouringListApConfig: {
                    model_type: 'NeighbouringAPListConfiguration',
                    minSignal: -85,
                    maxAps: 25,
                  },
                  minAutoCellSize: -80,
                  perimeterDetectionEnabled: true,
                  bestAPSteerType: 'both',
                  deauthAttackDetection: null,
                  allowedChannelsPowerLevels: [],
                  activeChannel: 6,
                },
                is5GHzU: {
                  model_type: 'ElementRadioConfiguration',
                  radioType: 'is5GHzU',
                  channelNumber: 149,
                  manualChannelNumber: 149,
                  backupChannelNumber: 154,
                  autoChannelSelection: true,
                  channelBandwidth: 'is80MHz',
                  bannedChannels: [],
                  allowedChannels: [],
                  rxCellSizeDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  probeResponseThresholdDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  clientDisconnectThresholdDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  eirpTxPower: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: 18,
                  },
                  bestApEnabled: null,
                  neighbouringListApConfig: {
                    model_type: 'NeighbouringAPListConfiguration',
                    minSignal: -85,
                    maxAps: 25,
                  },
                  minAutoCellSize: -80,
                  perimeterDetectionEnabled: true,
                  bestAPSteerType: 'both',
                  deauthAttackDetection: null,
                  allowedChannelsPowerLevels: [],
                  activeChannel: 149,
                },
                is5GHzL: {
                  model_type: 'ElementRadioConfiguration',
                  radioType: 'is5GHzL',
                  channelNumber: 36,
                  manualChannelNumber: 36,
                  backupChannelNumber: 44,
                  autoChannelSelection: true,
                  channelBandwidth: 'is80MHz',
                  bannedChannels: [],
                  allowedChannels: [],
                  rxCellSizeDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  probeResponseThresholdDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  clientDisconnectThresholdDb: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: -90,
                  },
                  eirpTxPower: {
                    model_type: 'AutoOrManualValue',
                    auto: true,
                    value: 18,
                  },
                  bestApEnabled: null,
                  neighbouringListApConfig: {
                    model_type: 'NeighbouringAPListConfiguration',
                    minSignal: -85,
                    maxAps: 25,
                  },
                  minAutoCellSize: -80,
                  perimeterDetectionEnabled: true,
                  bestAPSteerType: 'both',
                  deauthAttackDetection: null,
                  allowedChannelsPowerLevels: [],
                  activeChannel: 36,
                },
              },
              advancedRadioMap: {
                is2dot4GHz: {
                  model_type: 'RadioConfiguration',
                  radioType: 'is2dot4GHz',
                  radioAdminState: 'enabled',
                  fragmentationThresholdBytes: 2346,
                  rtsCtsThreshold: 65535,
                  autoChannelSelection: 'disabled',
                  radioMode: 'modeN',
                  mimoMode: 'twoByTwo',
                  wmmState: 'enabled',
                  uapsdState: 'enabled',
                  maxNumClients: 100,
                  stationIsolation: 'disabled',
                  multicastRate: 'auto',
                  managementRate: 'auto',
                  activeScanSettings: {
                    model_type: 'ActiveScanSettings',
                    enabled: true,
                    scanFrequencySeconds: 10,
                    scanDurationMillis: 65,
                  },
                  channelHopSettings: {
                    model_type: 'ChannelHopSettings',
                    noiseFloorThresholdInDB: -75,
                    noiseFloorThresholdTimeInSeconds: 180,
                    nonWifiThresholdInPercentage: 50,
                    nonWifiThresholdTimeInSeconds: 180,
                    obssHopMode: 'NON_WIFI',
                  },
                  bestApSettings: {
                    model_type: 'RadioBestApSettings',
                    mlComputed: true,
                    dropInSnrPercentage: 20,
                    minLoadFactor: 50,
                  },
                  forceScanDuringVoice: 'disabled',
                  legacyBSSRate: 'enabled',
                  beaconInterval: 100,
                  deauthAttackDetection: null,
                },
                is5GHzU: {
                  model_type: 'RadioConfiguration',
                  radioType: 'is5GHzU',
                  radioAdminState: 'enabled',
                  fragmentationThresholdBytes: 2346,
                  rtsCtsThreshold: 65535,
                  autoChannelSelection: 'disabled',
                  radioMode: 'modeAC',
                  mimoMode: 'twoByTwo',
                  wmmState: 'enabled',
                  uapsdState: 'enabled',
                  maxNumClients: 100,
                  stationIsolation: 'disabled',
                  multicastRate: 'auto',
                  managementRate: 'auto',
                  activeScanSettings: {
                    model_type: 'ActiveScanSettings',
                    enabled: true,
                    scanFrequencySeconds: 10,
                    scanDurationMillis: 65,
                  },
                  channelHopSettings: {
                    model_type: 'ChannelHopSettings',
                    noiseFloorThresholdInDB: -75,
                    noiseFloorThresholdTimeInSeconds: 180,
                    nonWifiThresholdInPercentage: 50,
                    nonWifiThresholdTimeInSeconds: 180,
                    obssHopMode: 'NON_WIFI',
                  },
                  bestApSettings: {
                    model_type: 'RadioBestApSettings',
                    mlComputed: true,
                    dropInSnrPercentage: 30,
                    minLoadFactor: 40,
                  },
                  forceScanDuringVoice: 'disabled',
                  legacyBSSRate: 'enabled',
                  beaconInterval: 100,
                  deauthAttackDetection: null,
                },
                is5GHzL: {
                  model_type: 'RadioConfiguration',
                  radioType: 'is5GHzL',
                  radioAdminState: 'enabled',
                  fragmentationThresholdBytes: 2346,
                  rtsCtsThreshold: 65535,
                  autoChannelSelection: 'disabled',
                  radioMode: 'modeAC',
                  mimoMode: 'twoByTwo',
                  wmmState: 'enabled',
                  uapsdState: 'enabled',
                  maxNumClients: 100,
                  stationIsolation: 'disabled',
                  multicastRate: 'auto',
                  managementRate: 'auto',
                  activeScanSettings: {
                    model_type: 'ActiveScanSettings',
                    enabled: true,
                    scanFrequencySeconds: 10,
                    scanDurationMillis: 65,
                  },
                  channelHopSettings: {
                    model_type: 'ChannelHopSettings',
                    noiseFloorThresholdInDB: -75,
                    noiseFloorThresholdTimeInSeconds: 180,
                    nonWifiThresholdInPercentage: 50,
                    nonWifiThresholdTimeInSeconds: 180,
                    obssHopMode: 'NON_WIFI',
                  },
                  bestApSettings: {
                    model_type: 'RadioBestApSettings',
                    mlComputed: true,
                    dropInSnrPercentage: 30,
                    minLoadFactor: 40,
                  },
                  forceScanDuringVoice: 'disabled',
                  legacyBSSRate: 'enabled',
                  beaconInterval: 100,
                  deauthAttackDetection: null,
                },
              },
            },
            profile: {
              name: 'ApProfile-3-radios',
              childProfiles: [
                {
                  id: '3',
                  name: 'TipWlan-cloud-3-radios',
                  details: {
                    model_type: 'SsidConfiguration',
                    ssid: 'TipWlan-cloud-3-radios',
                    appliedRadios: ['is2dot4GHz', 'is5GHzL', 'is5GHzU'],
                    ssidAdminState: 'enabled',
                    secureMode: 'open',
                    vlanId: 1,
                    keyStr: null,
                    broadcastSsid: 'enabled',
                    keyRefresh: 0,
                    noLocalSubnets: false,
                    radiusServiceName: null,
                    captivePortalId: null,
                    bandwidthLimitDown: 0,
                    bandwidthLimitUp: 0,
                    clientBandwidthLimitDown: 0,
                    clientBandwidthLimitUp: 0,
                    videoTrafficOnly: false,
                    radioBasedConfigs: {
                      is5GHz: {
                        model_type: 'RadioBasedSsidConfiguration',
                        enable80211r: null,
                        enable80211k: null,
                        enable80211v: null,
                      },
                      is2dot4GHz: {
                        model_type: 'RadioBasedSsidConfiguration',
                        enable80211r: null,
                        enable80211k: null,
                        enable80211v: null,
                      },
                      is5GHzU: {
                        model_type: 'RadioBasedSsidConfiguration',
                        enable80211r: null,
                        enable80211k: null,
                        enable80211v: null,
                      },
                      is5GHzL: {
                        model_type: 'RadioBasedSsidConfiguration',
                        enable80211r: null,
                        enable80211k: null,
                        enable80211v: null,
                      },
                    },
                    bonjourGatewayProfileId: null,
                    enable80211w: null,
                    wepConfig: null,
                    forwardMode: null,
                    profileType: 'ssid',
                  },
                  __typename: 'Profile',
                },
              ],
              __typename: 'Profile',
            },
            status: {
              firmware: {
                detailsJSON: {},
                __typename: 'Status',
              },
              protocol: {
                detailsJSON: {
                  model_type: 'EquipmentProtocolStatusData',
                  poweredOn: true,
                  protocolState: 'ready',
                  reportedHwVersion: null,
                  reportedSwVersion: null,
                  reportedSwAltVersion: null,
                  cloudProtocolVersion: null,
                  reportedIpV4Addr: '192.168.1.124',
                  reportedIpV6Addr: 'fe80:0:0:0:218:b4ff:fec7:1fbe',
                  reportedMacAddr: {
                    model_type: 'MacAddress',
                    address: 'dJzjEKqK',
                    addressAsString: '74:9c:e3:10:aa:8a',
                  },
                  countryCode: null,
                  systemName: null,
                  systemContact: null,
                  systemLocation: null,
                  bandPlan: null,
                  serialNumber: 'serial-ap-1',
                  baseMacAddress: {
                    model_type: 'MacAddress',
                    address: 'dJzjEKqK',
                    addressAsString: '74:9c:e3:10:aa:8a',
                  },
                  reportedApcAddress: null,
                  lastApcUpdate: null,
                  isApcConnected: null,
                  ipBasedConfiguration: null,
                  reportedSku: null,
                  reportedCC: null,
                  radiusProxyAddress: null,
                  reportedCfgDataVersion: null,
                  cloudCfgDataVersion: null,
                  useTroubleshotThrottleConfig: null,
                  dataThrottleCfgModeChanged: null,
                  statusDataType: 'PROTOCOL',
                },
                details: {
                  reportedMacAddr: '74:9c:e3:10:aa:8a',
                  manufacturer: 'KodaCloud Canada Inc.',
                  __typename: 'StatusDetails',
                },
                __typename: 'Status',
              },
              radioUtilization: {
                detailsJSON: {
                  model_type: 'RadioUtilizationReport',
                  radioUtilization: {
                    is2dot4GHz: {
                      model_type: 'EquipmentPerRadioUtilizationDetails',
                      wifiFromOtherBss: {
                        model_type: 'MinMaxAvgValueInt',
                        minValue: 3,
                        maxValue: 5,
                        avgValue: 9,
                      },
                    },
                    is5GHzU: {
                      model_type: 'EquipmentPerRadioUtilizationDetails',
                      wifiFromOtherBss: {
                        model_type: 'MinMaxAvgValueInt',
                        minValue: 3,
                        maxValue: 7,
                        avgValue: 5,
                      },
                    },
                    is5GHzL: {
                      model_type: 'EquipmentPerRadioUtilizationDetails',
                      wifiFromOtherBss: {
                        model_type: 'MinMaxAvgValueInt',
                        minValue: 1,
                        maxValue: 8,
                        avgValue: 7,
                      },
                    },
                  },
                  capacityDetails: {
                    is2dot4GHz: {
                      model_type: 'EquipmentCapacityDetails',
                      totalCapacity: 90,
                      availableCapacity: 89,
                      unavailableCapacity: 1,
                      unusedCapacity: 21,
                      usedCapacity: 68,
                    },
                    is5GHzU: {
                      model_type: 'EquipmentCapacityDetails',
                      totalCapacity: 86,
                      availableCapacity: 62,
                      unavailableCapacity: 24,
                      unusedCapacity: 6,
                      usedCapacity: 56,
                    },
                    is5GHzL: {
                      model_type: 'EquipmentCapacityDetails',
                      totalCapacity: 79,
                      availableCapacity: 52,
                      unavailableCapacity: 27,
                      unusedCapacity: 25,
                      usedCapacity: 27,
                    },
                  },
                  avgNoiseFloor: {
                    is2dot4GHz: -62,
                    is5GHzU: -82,
                    is5GHzL: -80,
                  },
                  statusDataType: 'RADIO_UTILIZATION',
                },
                __typename: 'Status',
              },
              clientDetails: {
                detailsJSON: {},
                details: null,
                __typename: 'Status',
              },
              osPerformance: {
                detailsJSON: {
                  model_type: 'OperatingSystemPerformance',
                  numCamiCrashes: 0,
                  uptimeInSeconds: 2423,
                  avgCpuUtilization: 12.615509,
                  avgCpuPerCore: [66.527954, 9.931038],
                  avgFreeMemoryKb: 55316,
                  totalAvailableMemoryKb: 512000,
                  avgCpuTemperature: 35.838608,
                  statusDataType: 'OS_PERFORMANCE',
                },
                __typename: 'Status',
              },
              __typename: 'EquipmentStatus',
            },
            model: 'ecw5211',
            alarmsCount: 0,
            alarms: [],
            __typename: 'Equipment',
          },
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: GET_EQUIPMENT,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
  getAllProfiles: {
    success: {
      request: {
        query: GET_ALL_PROFILES,
        variables: {
          customerId: 2,
          type: 'equipment_ap',
        },
      },
      result: {
        data: {
          getAllProfiles: {
            items: [
              {
                id: '6',
                name: 'ApProfile-3-radios',
                profileType: 'equipment_ap',
                details: {
                  model_type: 'ApNetworkConfiguration',
                  networkConfigVersion: 'AP-1',
                  equipmentType: 'AP',
                  vlanNative: true,
                  vlan: 0,
                  ntpServer: {
                    model_type: 'AutoOrManualString',
                    auto: true,
                    value: 'pool.ntp.org',
                  },
                  syslogRelay: null,
                  rtlsSettings: null,
                  syntheticClientEnabled: true,
                  ledControlEnabled: true,
                  equipmentDiscovery: false,
                  radioMap: {
                    is2dot4GHz: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                    is5GHzU: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                    is5GHzL: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                  },
                  profileType: 'equipment_ap',
                },
                childProfiles: [
                  {
                    id: '3',
                    name: 'TipWlan-cloud-3-radios',
                    details: {
                      model_type: 'SsidConfiguration',
                      ssid: 'TipWlan-cloud-3-radios',
                      appliedRadios: ['is2dot4GHz', 'is5GHzL', 'is5GHzU'],
                      ssidAdminState: 'enabled',
                      secureMode: 'open',
                      vlanId: 1,
                      keyStr: null,
                      broadcastSsid: 'enabled',
                      keyRefresh: 0,
                      noLocalSubnets: false,
                      radiusServiceName: null,
                      captivePortalId: null,
                      bandwidthLimitDown: 0,
                      bandwidthLimitUp: 0,
                      clientBandwidthLimitDown: 0,
                      clientBandwidthLimitUp: 0,
                      videoTrafficOnly: false,
                      radioBasedConfigs: {
                        is5GHz: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is2dot4GHz: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is5GHzU: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is5GHzL: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                      },
                      bonjourGatewayProfileId: null,
                      enable80211w: null,
                      wepConfig: null,
                      forwardMode: null,
                      profileType: 'ssid',
                    },
                    __typename: 'Profile',
                  },
                ],
                __typename: 'Profile',
              },
              {
                id: '7',
                name: 'ApProfile-2-radios',
                profileType: 'equipment_ap',
                details: {
                  model_type: 'ApNetworkConfiguration',
                  networkConfigVersion: 'AP-1',
                  equipmentType: 'AP',
                  vlanNative: true,
                  vlan: 0,
                  ntpServer: {
                    model_type: 'AutoOrManualString',
                    auto: true,
                    value: 'pool.ntp.org',
                  },
                  syslogRelay: null,
                  rtlsSettings: null,
                  syntheticClientEnabled: true,
                  ledControlEnabled: true,
                  equipmentDiscovery: false,
                  radioMap: {
                    is5GHz: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                    is2dot4GHz: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                  },
                  profileType: 'equipment_ap',
                },
                childProfiles: [
                  {
                    id: '4',
                    name: 'TipWlan-cloud-2-radios',
                    details: {
                      model_type: 'SsidConfiguration',
                      ssid: 'TipWlan-cloud-2-radios',
                      appliedRadios: ['is2dot4GHz', 'is5GHz'],
                      ssidAdminState: 'enabled',
                      secureMode: 'open',
                      vlanId: 1,
                      keyStr: null,
                      broadcastSsid: 'enabled',
                      keyRefresh: 0,
                      noLocalSubnets: false,
                      radiusServiceName: null,
                      captivePortalId: null,
                      bandwidthLimitDown: 0,
                      bandwidthLimitUp: 0,
                      clientBandwidthLimitDown: 0,
                      clientBandwidthLimitUp: 0,
                      videoTrafficOnly: false,
                      radioBasedConfigs: {
                        is5GHz: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is2dot4GHz: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is5GHzU: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is5GHzL: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                      },
                      bonjourGatewayProfileId: null,
                      enable80211w: null,
                      wepConfig: null,
                      forwardMode: null,
                      profileType: 'ssid',
                    },
                    __typename: 'Profile',
                  },
                ],
                __typename: 'Profile',
              },
              {
                id: '8',
                name: 'EnterpriseApProfile',
                profileType: 'equipment_ap',
                details: {
                  model_type: 'ApNetworkConfiguration',
                  networkConfigVersion: 'AP-1',
                  equipmentType: 'AP',
                  vlanNative: true,
                  vlan: 0,
                  ntpServer: {
                    model_type: 'AutoOrManualString',
                    auto: true,
                    value: 'pool.ntp.org',
                  },
                  syslogRelay: null,
                  rtlsSettings: null,
                  syntheticClientEnabled: true,
                  ledControlEnabled: true,
                  equipmentDiscovery: false,
                  radioMap: {
                    is5GHz: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                    is2dot4GHz: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                    is5GHzU: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                    is5GHzL: {
                      model_type: 'RadioProfileConfiguration',
                      bestApEnabled: true,
                      bestAPSteerType: 'both',
                    },
                  },
                  profileType: 'equipment_ap',
                },
                childProfiles: [
                  {
                    id: '2',
                    name: 'TipWlan-cloud-Enterprise',
                    details: {
                      model_type: 'SsidConfiguration',
                      ssid: 'Default-SSID-1597172801679',
                      appliedRadios: ['is2dot4GHz', 'is5GHzL', 'is5GHzU'],
                      ssidAdminState: 'enabled',
                      secureMode: 'wpaEAP',
                      vlanId: 1,
                      keyStr: 'testing123',
                      broadcastSsid: 'enabled',
                      keyRefresh: 0,
                      noLocalSubnets: false,
                      radiusServiceName: 'Radius-Profile',
                      captivePortalId: null,
                      bandwidthLimitDown: 0,
                      bandwidthLimitUp: 0,
                      clientBandwidthLimitDown: 0,
                      clientBandwidthLimitUp: 0,
                      videoTrafficOnly: false,
                      radioBasedConfigs: {
                        is5GHz: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is2dot4GHz: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is5GHzU: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                        is5GHzL: {
                          model_type: 'RadioBasedSsidConfiguration',
                          enable80211r: null,
                          enable80211k: null,
                          enable80211v: null,
                        },
                      },
                      bonjourGatewayProfileId: null,
                      enable80211w: null,
                      wepConfig: null,
                      forwardMode: null,
                      profileType: 'ssid',
                    },
                    __typename: 'Profile',
                  },
                ],
                __typename: 'Profile',
              },
            ],
            context: {
              cursor:
                'bnVsbEBAQHsibW9kZWxfdHlwZSI6IkNvbnRleHRDaGlsZHJlbiIsImNoaWxkcmVuIjp7fX1AQEBudWxs',
              lastPage: true,
              __typename: 'PaginationContext',
            },
            __typename: 'ProfilePagination',
          },
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: GET_ALL_PROFILES,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
  getAllFirmware: {
    success: {
      request: {
        query: GET_ALL_FIRMWARE,
        // variables: {},
      },
      result: {
        data: {
          getAllFirmware: [
            {
              id: '1',
              modelId: 'ap2220',
              versionName: 'ap2220-2020-06-25-ce03472',
              description: '',
              filename:
                'https://tip-read:tip-read@tip.jfrog.io/artifactory/tip-wlan-ap-firmware/ap2220/ap2220-2020-06-25-ce03472.tar.gz',
              commit: 'ce03472',
              releaseDate: '1597172802689',
              __typename: 'Firmware',
            },
            {
              id: '2',
              modelId: 'ea8300',
              versionName: 'ea8300-2020-06-25-ce03472',
              description: '',
              filename:
                'https://tip-read:tip-read@tip-read:tip-read@tip.jfrog.io/artifactory/tip-wlan-ap-firmware/ea8300/ea8300-2020-06-25-ce03472.tar.gz',
              commit: 'ce03472',
              releaseDate: '1597172802692',
              __typename: 'Firmware',
            },
            {
              id: '3',
              modelId: 'ea8300-ca',
              versionName: 'ea8300-2020-06-25-ce03472',
              description: '',
              filename:
                'https://tip-read:tip-read@tip.jfrog.io/artifactory/tip-wlan-ap-firmware/ea8300/ea8300-2020-06-25-ce03472.tar.gz',
              commit: 'ce03472',
              releaseDate: '1597172802692',
              __typename: 'Firmware',
            },
            {
              id: '4',
              modelId: 'ecw5211',
              versionName: 'ecw5211-2020-06-26-4ff7208',
              description: '',
              filename:
                'https://tip-read:tip-read@tip.jfrog.io/artifactory/tip-wlan-ap-firmware/ecw5211/ecw5211-2020-06-26-4ff7208.tar.gz',
              commit: '4ff7208',
              releaseDate: '1597172802692',
              __typename: 'Firmware',
            },
            {
              id: '5',
              modelId: 'ecw5410',
              versionName: 'ecw5410-2020-06-25-ce03472',
              description: '',
              filename:
                'https://tip-read:tip-read@tip.jfrog.io/artifactory/tip-wlan-ap-firmware/ecw5410/ecw5410-2020-06-25-ce03472.tar.gz',
              commit: 'ce03472',
              releaseDate: '1597172802692',
              __typename: 'Firmware',
            },
          ],
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: GET_ALL_FIRMWARE,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
  filterServiceMetrics: {
    success: {
      request: {
        query: FILTER_SERVICE_METRICS,
        variables: {
          customerId: 2,
          fromTime: '1597238999328',
          toTime: '1597242599328',
          equipmentIds: ['2'],
          dataTypes: ['ApNode'],
          limit: 100,
        },
      },
      result: {
        data: {
          filterServiceMetrics: {
            items: [],
            context: {
              lastPage: true,
              cursor:
                'bnVsbEBAQHsibW9kZWxfdHlwZSI6IkNvbnRleHRDaGlsZHJlbiIsImNoaWxkcmVuIjp7fX1AQEBudWxs',
              __typename: 'PaginationContext',
            },
            __typename: 'ServiceMetricPagination',
          },
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: FILTER_SERVICE_METRICS,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
  updateEquipment: {
    success: {
      request: {
        query: UPDATE_EQUIPMENT,
        variables: {
          customerId: 2,
          statusDataTypes: ['CUSTOMER_DASHBOARD'],
        },
      },
      result: {
        data: {},
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: UPDATE_EQUIPMENT,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
  updateEquipmentFirmware: {
    success: {
      request: {
        query: UPDATE_EQUIPMENT_FIRMWARE,
        variables: {
          customerId: 2,
          statusDataTypes: ['CUSTOMER_DASHBOARD'],
        },
      },
      result: {
        data: {},
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: UPDATE_EQUIPMENT_FIRMWARE,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
};
