import { FILTER_SYSTEM_EVENTS, GET_ALL_STATUS } from 'graphql/queries';

export const dashboardQueryMock = {
  filterSystemEvents: {
    success: {
      request: {
        query: FILTER_SYSTEM_EVENTS,
        variables: {
          customerId: 2,
          fromTime: '1234',
          toTime: '1234',
          equipmentIds: [0],
          dataTypes: ['StatusChangedEvent'],
          limit: 3000,
        },
      },
      result: {
        data: {
          filterSystemEvents: {
            items: [
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597158402687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597158402687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597158600000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 950,
                        is5GHzU: 950,
                        is5GHzL: 550,
                      },
                      trafficBytesDownstream: 73369055,
                      trafficBytesUpstream: 8325535,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597158402687,
                    lastModifiedTimestamp: 1597158402687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597158702687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597158702687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597158900000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 950,
                        is5GHzU: 200,
                        is5GHzL: 550,
                      },
                      trafficBytesDownstream: 49536405,
                      trafficBytesUpstream: 11689996,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597158702687,
                    lastModifiedTimestamp: 1597158702687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597159002687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597159002687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597159200000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 350,
                        is5GHzU: 800,
                        is5GHzL: 950,
                      },
                      trafficBytesDownstream: 31731308,
                      trafficBytesUpstream: 24059870,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597159002687,
                    lastModifiedTimestamp: 1597159002687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597159302687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597159302687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597159500000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 100,
                        is5GHzU: 600,
                        is5GHzL: 450,
                      },
                      trafficBytesDownstream: 63193149,
                      trafficBytesUpstream: 73805821,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597159302687,
                    lastModifiedTimestamp: 1597159302687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597159602687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597159602687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597159800000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 850,
                        is5GHzU: 700,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 67675061,
                      trafficBytesUpstream: 36260729,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597159602687,
                    lastModifiedTimestamp: 1597159602687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597159902687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597159902687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597160100000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 250,
                        is5GHzU: 450,
                        is5GHzL: 150,
                      },
                      trafficBytesDownstream: 92741531,
                      trafficBytesUpstream: 27578452,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597159902687,
                    lastModifiedTimestamp: 1597159902687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597160202687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597160202687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597160400000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 50,
                        is5GHzU: 700,
                        is5GHzL: 50,
                      },
                      trafficBytesDownstream: 66214793,
                      trafficBytesUpstream: 46890326,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597160202687,
                    lastModifiedTimestamp: 1597160202687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597160502687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597160502687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597160700000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 750,
                        is5GHzU: 100,
                        is5GHzL: 750,
                      },
                      trafficBytesDownstream: 33864257,
                      trafficBytesUpstream: 64380317,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597160502687,
                    lastModifiedTimestamp: 1597160502687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597160802687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597160802687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597161000000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 850,
                        is5GHzU: 300,
                        is5GHzL: 500,
                      },
                      trafficBytesDownstream: 32065510,
                      trafficBytesUpstream: 52435461,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597160802687,
                    lastModifiedTimestamp: 1597160802687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597161102687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597161102687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597161300000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 350,
                        is5GHzU: 550,
                        is5GHzL: 450,
                      },
                      trafficBytesDownstream: 17420342,
                      trafficBytesUpstream: 67293819,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597161102687,
                    lastModifiedTimestamp: 1597161102687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597161402687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597161402687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597161600000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 350,
                        is5GHzU: 700,
                        is5GHzL: 150,
                      },
                      trafficBytesDownstream: 32992043,
                      trafficBytesUpstream: 39357794,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597161402687,
                    lastModifiedTimestamp: 1597161402687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597161702687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597161702687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597161900000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 900,
                        is5GHzU: 800,
                        is5GHzL: 700,
                      },
                      trafficBytesDownstream: 39421643,
                      trafficBytesUpstream: 54164486,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597161702687,
                    lastModifiedTimestamp: 1597161702687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597162002687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597162002687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597162200000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 250,
                        is5GHzU: 550,
                        is5GHzL: 100,
                      },
                      trafficBytesDownstream: 88296021,
                      trafficBytesUpstream: 40947157,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597162002687,
                    lastModifiedTimestamp: 1597162002687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597162302687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597162302687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597162500000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 200,
                        is5GHzU: 100,
                        is5GHzL: 900,
                      },
                      trafficBytesDownstream: 35731139,
                      trafficBytesUpstream: 98493682,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597162302687,
                    lastModifiedTimestamp: 1597162302687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597162602687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597162602687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597162800000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 200,
                        is5GHzU: 700,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 57117010,
                      trafficBytesUpstream: 18245422,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597162602687,
                    lastModifiedTimestamp: 1597162602687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597162902687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597162902687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597163100000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 150,
                        is5GHzU: 850,
                        is5GHzL: 350,
                      },
                      trafficBytesDownstream: 79024435,
                      trafficBytesUpstream: 76139078,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597162902687,
                    lastModifiedTimestamp: 1597162902687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597163202687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597163202687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597163400000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 600,
                        is5GHzU: 950,
                        is5GHzL: 50,
                      },
                      trafficBytesDownstream: 40129633,
                      trafficBytesUpstream: 50628101,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597163202687,
                    lastModifiedTimestamp: 1597163202687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597163502687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597163502687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597163700000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 50,
                        is5GHzU: 400,
                        is5GHzL: 850,
                      },
                      trafficBytesDownstream: 90794912,
                      trafficBytesUpstream: 87803062,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597163502687,
                    lastModifiedTimestamp: 1597163502687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597163802687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597163802687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597164000000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 750,
                        is5GHzU: 450,
                        is5GHzL: 350,
                      },
                      trafficBytesDownstream: 77823361,
                      trafficBytesUpstream: 8619152,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597163802687,
                    lastModifiedTimestamp: 1597163802687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597164102687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597164102687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597164300000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 450,
                        is5GHzU: 850,
                        is5GHzL: 900,
                      },
                      trafficBytesDownstream: 51975083,
                      trafficBytesUpstream: 57989157,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597164102687,
                    lastModifiedTimestamp: 1597164102687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597164402687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597164402687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597164600000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 750,
                        is5GHzU: 400,
                        is5GHzL: 100,
                      },
                      trafficBytesDownstream: 67703703,
                      trafficBytesUpstream: 81575276,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597164402687,
                    lastModifiedTimestamp: 1597164402687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597164702687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597164702687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597164900000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 750,
                        is5GHzU: 500,
                        is5GHzL: 50,
                      },
                      trafficBytesDownstream: 74845468,
                      trafficBytesUpstream: 89654299,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597164702687,
                    lastModifiedTimestamp: 1597164702687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597165002687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597165002687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597165200000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 750,
                        is5GHzU: 850,
                        is5GHzL: 350,
                      },
                      trafficBytesDownstream: 14362752,
                      trafficBytesUpstream: 21575719,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597165002687,
                    lastModifiedTimestamp: 1597165002687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597165302687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597165302687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597165500000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 500,
                        is5GHzU: 350,
                        is5GHzL: 350,
                      },
                      trafficBytesDownstream: 55624613,
                      trafficBytesUpstream: 18403045,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597165302687,
                    lastModifiedTimestamp: 1597165302687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597165602687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597165602687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597165800000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 250,
                        is5GHzU: 100,
                        is5GHzL: 650,
                      },
                      trafficBytesDownstream: 32406237,
                      trafficBytesUpstream: 9321124,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597165602687,
                    lastModifiedTimestamp: 1597165602687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597165902687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597165902687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597166100000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 800,
                        is5GHzU: 900,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 102358137,
                      trafficBytesUpstream: 83043878,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597165902687,
                    lastModifiedTimestamp: 1597165902687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597166202687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597166202687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597166400000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 250,
                        is5GHzU: 750,
                        is5GHzL: 550,
                      },
                      trafficBytesDownstream: 78728576,
                      trafficBytesUpstream: 61771764,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597166202687,
                    lastModifiedTimestamp: 1597166202687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597166502687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597166502687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597166700000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 350,
                        is5GHzU: 50,
                        is5GHzL: 900,
                      },
                      trafficBytesDownstream: 83892788,
                      trafficBytesUpstream: 62005096,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597166502687,
                    lastModifiedTimestamp: 1597166502687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597166802687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597166802687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597167000000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 300,
                        is5GHzU: 800,
                        is5GHzL: 300,
                      },
                      trafficBytesDownstream: 32694385,
                      trafficBytesUpstream: 99895377,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597166802687,
                    lastModifiedTimestamp: 1597166802687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597167102687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597167102687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597167300000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 500,
                        is5GHzU: 50,
                        is5GHzL: 300,
                      },
                      trafficBytesDownstream: 21836878,
                      trafficBytesUpstream: 52898732,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597167102687,
                    lastModifiedTimestamp: 1597167102687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597167402687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597167402687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597167600000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 500,
                        is5GHzU: 850,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 19574872,
                      trafficBytesUpstream: 70064297,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597167402687,
                    lastModifiedTimestamp: 1597167402687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597167702687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597167702687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597167900000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 500,
                        is5GHzU: 600,
                        is5GHzL: 200,
                      },
                      trafficBytesDownstream: 94037995,
                      trafficBytesUpstream: 59897992,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597167702687,
                    lastModifiedTimestamp: 1597167702687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597168002687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597168002687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597168200000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 150,
                        is5GHzU: 950,
                        is5GHzL: 300,
                      },
                      trafficBytesDownstream: 22323028,
                      trafficBytesUpstream: 47719461,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597168002687,
                    lastModifiedTimestamp: 1597168002687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597168302687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597168302687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597168500000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 250,
                        is5GHzU: 750,
                        is5GHzL: 750,
                      },
                      trafficBytesDownstream: 72380974,
                      trafficBytesUpstream: 29092180,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597168302687,
                    lastModifiedTimestamp: 1597168302687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597168602687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597168602687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597168800000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 750,
                        is5GHzU: 50,
                        is5GHzL: 450,
                      },
                      trafficBytesDownstream: 71737737,
                      trafficBytesUpstream: 16846591,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597168602687,
                    lastModifiedTimestamp: 1597168602687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597168902687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597168902687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597169100000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 100,
                        is5GHzU: 800,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 43315721,
                      trafficBytesUpstream: 43200444,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597168902687,
                    lastModifiedTimestamp: 1597168902687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597169202687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597169202687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597169400000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 800,
                        is5GHzU: 700,
                        is5GHzL: 550,
                      },
                      trafficBytesDownstream: 46611457,
                      trafficBytesUpstream: 45091435,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597169202687,
                    lastModifiedTimestamp: 1597169202687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597169502687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597169502687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597169700000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 550,
                        is5GHzU: 900,
                        is5GHzL: 50,
                      },
                      trafficBytesDownstream: 21718969,
                      trafficBytesUpstream: 25622310,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597169502687,
                    lastModifiedTimestamp: 1597169502687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597169802687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597169802687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597170000000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 50,
                        is5GHzU: 100,
                        is5GHzL: 950,
                      },
                      trafficBytesDownstream: 78989275,
                      trafficBytesUpstream: 70042524,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597169802687,
                    lastModifiedTimestamp: 1597169802687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597170102687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597170102687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597170300000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 200,
                        is5GHzU: 200,
                        is5GHzL: 150,
                      },
                      trafficBytesDownstream: 39293241,
                      trafficBytesUpstream: 30501297,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597170102687,
                    lastModifiedTimestamp: 1597170102687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597170402687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597170402687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597170600000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 400,
                        is5GHzU: 750,
                        is5GHzL: 700,
                      },
                      trafficBytesDownstream: 89661395,
                      trafficBytesUpstream: 46960760,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597170402687,
                    lastModifiedTimestamp: 1597170402687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597170702687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597170702687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597170900000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 850,
                        is5GHzU: 50,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 71088852,
                      trafficBytesUpstream: 15063282,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597170702687,
                    lastModifiedTimestamp: 1597170702687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597171002687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597171002687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597171200000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 950,
                        is5GHzU: 650,
                        is5GHzL: 300,
                      },
                      trafficBytesDownstream: 54001704,
                      trafficBytesUpstream: 58226286,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597171002687,
                    lastModifiedTimestamp: 1597171002687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597171302687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597171302687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597171500000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 800,
                        is5GHzU: 500,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 77842211,
                      trafficBytesUpstream: 66811239,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597171302687,
                    lastModifiedTimestamp: 1597171302687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597171602687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597171602687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597171800000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 800,
                        is5GHzU: 50,
                        is5GHzL: 400,
                      },
                      trafficBytesDownstream: 75849723,
                      trafficBytesUpstream: 67758720,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597171602687,
                    lastModifiedTimestamp: 1597171602687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597171902687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597171902687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597172100000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 200,
                      },
                      trafficBytesDownstream: 39159942,
                      trafficBytesUpstream: 29122693,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597171902687,
                    lastModifiedTimestamp: 1597171902687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597172202687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597172202687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597172400000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is5GHzU: 100,
                        is5GHzL: 200,
                      },
                      trafficBytesDownstream: 58971977,
                      trafficBytesUpstream: 33963309,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597172202687,
                    lastModifiedTimestamp: 1597172202687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597172502687,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597172502687,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597172700000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 300,
                        is5GHzU: 200,
                        is5GHzL: 600,
                      },
                      trafficBytesDownstream: 91209596,
                      trafficBytesUpstream: 81378436,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597172502687,
                    lastModifiedTimestamp: 1597172502687,
                  },
                  equipmentId: 0,
                },
              },
              {
                model_type: 'SystemEventRecord',
                customerId: 2,
                equipmentId: 0,
                dataType: 'StatusChangedEvent',
                eventTimestamp: 1597172802684,
                details: {
                  model_type: 'StatusChangedEvent',
                  eventTimestamp: 1597172802684,
                  customerId: 2,
                  payload: {
                    model_type: 'Status',
                    customerId: 2,
                    equipmentId: 0,
                    statusDataType: 'CUSTOMER_DASHBOARD',
                    details: {
                      model_type: 'CustomerPortalDashboardStatus',
                      timeBucketId: 1597172700000,
                      timeBucketMs: 300000,
                      equipmentInServiceCount: 2,
                      equipmentWithClientsCount: 2,
                      associatedClientsCountPerRadio: {
                        is2dot4GHz: 850,
                        is5GHzU: 100,
                        is5GHzL: 150,
                      },
                      trafficBytesDownstream: 67050483,
                      trafficBytesUpstream: 79454339,
                      clientCountPerOui: {
                        '000001': 30,
                        '000000': 8,
                        '0F0F0F': 42,
                      },
                      totalProvisionedEquipment: 50,
                      equipmentCountPerOui: {
                        '749CE3': 50,
                        '1CEA0B': 1,
                        '3C2C99': 1,
                      },
                      statusDataType: 'CUSTOMER_DASHBOARD',
                    },
                    createdTimestamp: 1597172802684,
                    lastModifiedTimestamp: 1597172802684,
                  },
                  equipmentId: 0,
                },
              },
            ],
            context: {
              lastPage: true,
              cursor:
                'bnVsbEBAQHsibW9kZWxfdHlwZSI6IkNvbnRleHRDaGlsZHJlbiIsImNoaWxkcmVuIjp7fX1AQEBudWxs',
              __typename: 'PaginationContext',
            },
            __typename: 'SystemEventPagination',
          },
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: FILTER_SYSTEM_EVENTS,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
  getAllStatus: {
    success: {
      request: {
        query: GET_ALL_STATUS,
        variables: {
          customerId: 2,
          statusDataTypes: ['CUSTOMER_DASHBOARD'],
        },
      },
      result: {
        data: {
          getAllStatus: {
            items: [
              {
                customerId: '2',
                detailsJSON: {
                  model_type: 'CustomerPortalDashboardStatus',
                  timeBucketId: 1596814500000,
                  timeBucketMs: 300000,
                  equipmentInServiceCount: 2,
                  equipmentWithClientsCount: 2,
                  associatedClientsCountPerRadio: {
                    is2dot4GHz: 850,
                    is5GHzU: 700,
                    is5GHzL: 850,
                    is2dot4GHzT: 850,
                  },
                  trafficBytesDownstream: 61279355,
                  trafficBytesUpstream: 51684878,
                  clientCountPerOui: {
                    '000001': 30,
                    '000000': 8,
                    '0F0F0F': 42,
                  },
                  totalProvisionedEquipment: 50,
                  equipmentCountPerOui: {
                    '749CE3': 50,
                    '1CEA0B': 1,
                    '3C2C99': 1,
                  },
                  statusDataType: 'CUSTOMER_DASHBOARD',
                },
                details: {
                  equipmentCountPerOui: {
                    'KodaCloud Canada Inc.': 50,
                    'Edgecore Networks Corporation': 2,
                  },
                  clientCountPerOui: {
                    'Xerox Corporation': 38,
                    '0F0F0F': 42,
                  },
                  __typename: 'StatusDetails',
                },
                __typename: 'Status',
              },
            ],
            context: {
              lastPage: true,
              cursor:
                'bnVsbEBAQHsibW9kZWxfdHlwZSI6IkNvbnRleHRDaGlsZHJlbiIsImNoaWxkcmVuIjp7fX1AQEBudWxs',
              __typename: 'PaginationContext',
            },
            __typename: 'StatusPagination',
          },
        },
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
    error: {
      request: {
        query: GET_ALL_STATUS,
        variables: { customerId: 2 },
        errorPolicy: 'all',
      },
      result: {
        data: null,
        errors: [{}],
        loading: false,
        networkStatus: 7,
        stale: false,
      },
    },
  },
};
