export const AUTH_TOKEN = 'tip-auth-token';
export const COMPANY = 'Telecom Infra Project';

export const ACCESS_POINTS_TABLE_CLOUMNS = [
  {
    title: 'NAME',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'ALARMS',
    dataIndex: 'alarms',
    key: 'alarms',
  },
  { title: 'MODEL', dataIndex: 'model', key: 'model' },
  { title: 'IP', dataIndex: 'ip', key: 'ip' },
  { title: 'MAC', dataIndex: 'mac', key: 'mac' },
  { title: 'ASSET ID', dataIndex: 'assetId', key: 'assetId' },
  { title: 'UP TIME', dataIndex: 'upTime', key: 'upTime' },
  { title: 'PROFILE', dataIndex: 'profile', key: 'profile' },
  { title: 'CHANNEL', dataIndex: 'channel', key: 'channel' },
  { title: 'CAPACITY', dataIndex: 'capacity', key: 'capacity' },
  { title: 'NOISE FLOOR', dataIndex: 'noiseFloor', key: 'noiseFloor' },
  { title: 'DEVICES', dataIndex: 'devices', key: 'devices' },
];

export const CLIENT_DEVICES_TABLE_CLOUMNS = [
  {
    title: '',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Mac',
    dataIndex: 'mac',
    key: 'mac',
  },
  { title: 'OS/MODEL/MFR', dataIndex: 'osModelMfr', key: '1' },
  { title: 'IP', dataIndex: 'ip', key: '2' },
  { title: 'HOST NAME', dataIndex: 'hostName', key: '3' },
  { title: 'ACCESS POINT', dataIndex: 'accessPoint', key: '4' },
  { title: 'SSID', dataIndex: 'ssid', key: '5' },
  { title: 'BAND', dataIndex: 'band', key: '6' },
  { title: 'SIGNAL', dataIndex: 'signal', key: '7' },
  { title: 'STATUS', dataIndex: 'status', key: '8' },
];

export const CLIENT_DEVICES_TABLE_DATA = [
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 3,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 7,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 2,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 2,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 2,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 2,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
  {
    name: 'Laptop',
    mac: 'DO:C6:37:69:3E:FD',
    osModelMfr: 'Linux',
    ip: '100.115.92.2',
    hostName: 'LAPTOP-714LRTP6',
    accessPoint: 'AP100',
    ssid: 'TestUs',
    band: '5Ghz',
    signal: '-43 dBm',
    status: '39h 41m 25s Connected',
    locationId: 8,
  },
];
